CREATE SCHEMA Lab04;

CREATE TABLE Client (
	NIF INT NOT NULL PRIMARY KEY, CONSTRAINT NIF_ck CHECK (NIF BETWEEN 100000000 AND 999999999),
	Name VARCHAR(50) NOT NULL,
	Address VARCHAR(8), CONSTRAINT Address_ck CHECK (Address /* regex */)
	NLicense INT,
	);
